### ISSUE TITLE
Get `postcss-custom-media` working in local files and SFCs

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fuxt#104]
All the custom media queries defined in `/assets/css/media.css` don't seem to work when used in either `/assets/css/main.css` or in any component.

For example:
1) https://github.com/funkhaus/fuxt/blob/26b66d66189e8f2daa8bea61afbf9ae588f8f2fd/app/assets/css/main.css#L22-L26
2) https://github.com/funkhaus/fuxt/blob/26b66d66189e8f2daa8bea61afbf9ae588f8f2fd/app/components/global-header.vue#L18-L20

**Comment by drewbaker** [comment]
It works if we `@import` the media CSS into each component like this:
```
<style scoped>
@import "~/assets/css/media.css";

.global-header {
    background-color: #333;

    border: var(--lt-phone);

    @media (--lt-phone) {
        background-color: red;

        h2 {
            color: yellow;
        }
    }
}
</style>
```

So just need to figure out how to make that global so we don't have to `@import` on every component.

**Comment by drewbaker** [comment]
This might help: https://stackoverflow.com/questions/77205699/error-postcss-custom-media-importfrom-is-no-longer-supported

**Comment by lwaldner** [comment]
Fixed in https://github.com/funkhaus/fuxt/pull/115
