### ISSUE TITLE
Should we have a plugin for app setup code, or put in app.vue?

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fuxt#109]
What do you think is best practice for this sort of code?

https://github.com/funkhaus/fuxt/blob/26b66d66189e8f2daa8bea61afbf9ae588f8f2fd/app/app.vue#L2-L22

Should it be in App.vue or in a plugin? This is just one time setup code for the app. I have a similar thing to pre-populate the store with browser dimensions here: https://github.com/funkhaus/fuxt/blob/26b66d66189e8f2daa8bea61afbf9ae588f8f2fd/app/plugins/browser.client.ts

Curious what you think is the best practice way to do this.

**Comment by Diizzayy** [comment]
@drewbaker app initialization code such as what you have above can in-fact be suitably placed in either `app.vue` or a plugin, however though I'd recommend doing recommend using the latter approach ( initialization plugion ) for better separation of concerns, maintainability and extensibility ( whilst also allowing you to manage exactly when the said plugin is executed in correlation to other plugins you may end up having )

**Comment by drewbaker** [comment]
OK great, I moved to `init.ts` plugin
