### ISSUE TITLE
Nuxt-font module doesn't work with custom fonts

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fuxt#116]
Tried following this with custom fonts, and just get 404 errors for the detected custom fonts. The font dev tools show the fonts, but with empty "Generated CSS" area.

https://fonts.nuxt.com/advanced

**Comment by Diizzayy** [comment]
The `processCSSVariables` experiment flag must be enabled for the module to scan for font families specified via css vars.

```ts
fonts: {
    experimental: {
        processCSSVariables: true
    }
},
```

**Comment by drewbaker** [comment]
Fixed with https://github.com/funkhaus/fuxt/commit/16cebb66c153f405a94553345d6e0bd49bf762a3
