### ISSUE TITLE
WP Open API grandchildren fetching issue!

### ISSUE THREAD

**Issue by Sveb** [funkhaus/fuxt#127]
The issue I'm facing is the folowing.
This is my query:
![Screenshot 2024-12-19 at 19 12 36](https://github.com/user-attachments/assets/205a5568-c693-4536-abc9-d4f3d0a63405)

This is my backend:
![Screenshot 2024-12-19 at 19 11 59](https://github.com/user-attachments/assets/c9cc766c-72e4-47e1-9ca0-dab60f6db7d0)

This is what is getting returned:
![Screenshot 2024-12-19 at 19 11 39](https://github.com/user-attachments/assets/946f6658-919b-4442-9e49-6d01c4791509)

I was expecting to have all / 100 per page of the children (directors), but I'm only getting one per parent (director-category).

How do I query for all the grandchildren?

**Comment by drewbaker** [comment]
@Sveb Can you move this issue over to fuxt-api repo please.
