### ISSUE TITLE
New project - "Can't set headers after they are sent" 

### ISSUE THREAD

**Issue by stefanfmeyer** [funkhaus/fuxt#28]
Upon repo clone, npm install, changing .env vars and then running dev server. This error persistently pops up

ERROR: Error Can't set headers after they are sent.

Does anyone have any idea on why this is so persistent? 

My GQL endpoint WP backend is using your fuxt-backend theme.

**Comment by drewbaker** [comment]
Chances are the error is this:
```
Fatal error: Uncaught WPGraphQLGutenberg\Blocks\RegistryNotSourcedException: Client side block registry is missing. You need to open up gutenberg or load it from WPGraphQLGutenberg 
```

Basically just going to the GraphQL menu in the dashboard, then GraphQl Gutenberg and click the button on the page. It's some dumb stuff you have to do to pre-load Gutenberg to know about all the blocks it supports. #GutenbergSucks

**Comment by drewbaker** [comment]
I ran into this today I think. It was due to an old version of Node. I changed my package.json file to have this for my `engines`:

```
    "engines": {
        "node": "16.x"
    },
```

And then deleted my node_modules and package-lock and then `npm i` and it worked.
