### ISSUE TITLE
Allow GutenBerg Gallery To Allow for 1 Column

### ISSUE THREAD

**Issue by raffik16** [funkhaus/fuxt#29]
Right now the gallery is applying `2` columns to the image on the front end when it's clearly set in the editor to `1` column.

Currently on https://burch-api.flywheelsites.com/wp-admin/post.php?post=377&action=edit

```<figure class="wp-block-gallery columns-1 is-cropped"><ul class="blocks-gallery-grid"><li class="blocks-gallery-item"><figure><img src="https://burch-api.flywheelsites.com/wp-content/uploads/2021/10/210065695_240315107645572_2061082156188183164_n.jpg" alt="" data-id="388" class="wp-image-388"/></figure></li></ul></figure>```

**Comment by drewbaker** [comment]
Fixed with https://github.com/funkhaus/fuxt/commit/f638b42316e2602b5a54674c84f604773c123d40
