### ISSUE TITLE
Please, publish working demo

### ISSUE THREAD

**Issue by dadmor** [funkhaus/fuxt#4]

**Comment by drewbaker** [comment]
I'll try to get up a codesandbox demo this week for you. It requires a WordPress install too, so I'll have to figure out the best place for that too.

**Comment by drewbaker** [comment]
Deploying now to https://fuxt.funkhaus.us/

**Comment by xplodedthemes** [comment]
demo broken ?

**Comment by drewbaker** [comment]
Fixed now! Sorry about that. Made a change to the `wp-image` component to use `<figure>` and ended up with two `caption` fields in my GQL.

Also, I've been trying so hard to get `static` generation working, but it's broken as far as I can tell. https://github.com/nuxt/nuxt.js/issues/8107

**Comment by xplodedthemes** [comment]
-- Please reply above this line --


Hi Funkhaus/fuxt,

We received your email! Someone from our team will get back to you as
soon as possible.

(Monday - Friday / 9:00am - 5:00pm / GMT-4) We are developers and
like our beauty sleep ;-)

Thanks in advance for your patience and support.

---
XplodedThemes
https://xplodedthemes.com [1]

Links:
------
[1] https://xplodedthemes.com/
