### ISSUE TITLE
Auto SEO Plugin: Something went wrong with the plugin API.

### ISSUE THREAD

**Issue by liamb13** [funkhaus/fuxt#8]
Auto SEO plugin appears to no longer exist. Is this a WIP?

**Comment by drewbaker** [comment]
Sorry we made Auto SEO closed source as it did a lot of advanced stuff with AI that we had to use a cloud service for. So it costs us money to use it. Open to make it a paid plugin of some sort if you’re interested?

**Comment by liamb13** [comment]
What would the costs involved be? I'm just getting setup with Fuxt, but it seems like a solid tool thus far. Too early to call for certain, but I would be happy to support the dev team through paid plugins.

**Comment by drewbaker** [comment]
Thanks man, good to know someone is using it. 🤣

It would probably be a small month fee ($5 or something like that) and a per image uploaded fee, like cents per image or something like that as those get sent to a server for auto captioning etc. 

But fuxt works without the auto seo plugin. It’s totally optional.
